package store

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fioenix/overclaud/hatch/internal/mdfront"
	"github.com/fioenix/overclaud/hatch/internal/model"
	"github.com/fioenix/overclaud/hatch/internal/paths"
)

// KB reads and writes shared Knowledge Base entries.
type KB struct{ L paths.Layout }

// NewKB returns a knowledge base bound to a workspace layout.
func NewKB(l paths.Layout) *KB { return &KB{L: l} }

// List walks the kb/ subdirectories and returns all entries.
func (k *KB) List() ([]model.KBEntry, error) {
	root := k.L.KB()
	var out []model.KBEntry
	for _, sub := range []string{"decisions", "domain", "learnings"} {
		dir := filepath.Join(root, sub)
		ents, err := os.ReadDir(dir)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		for _, e := range ents {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			p := filepath.Join(dir, e.Name())
			raw, err := os.ReadFile(p)
			if err != nil {
				return nil, err
			}
			var entry model.KBEntry
			body, err := mdfront.Decode(raw, &entry)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", p, err)
			}
			entry.Body = body
			entry.Path = filepath.Join(sub, e.Name())
			out = append(out, entry)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}

// Query returns entries matching any of the given tags (case-insensitive).
func (k *KB) Query(tags []string) ([]model.KBEntry, error) {
	all, err := k.List()
	if err != nil {
		return nil, err
	}
	if len(tags) == 0 {
		return all, nil
	}
	want := map[string]bool{}
	for _, t := range tags {
		want[strings.ToLower(t)] = true
	}
	var out []model.KBEntry
	for _, e := range all {
		for _, t := range e.Tags {
			if want[strings.ToLower(t)] {
				out = append(out, e)
				break
			}
		}
	}
	return out, nil
}

// Add writes a new KB entry to its type subdirectory and returns the path.
func (k *KB) Add(e model.KBEntry) (string, error) {
	sub := model.KBSubdir(e.Type)
	dir := filepath.Join(k.L.KB(), sub)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	slug := e.ID
	if slug == "" {
		slug = slugify(e.Title)
	}
	name := slug + ".md"
	out, err := mdfront.Encode(e, e.Body)
	if err != nil {
		return "", err
	}
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, out, 0o644); err != nil {
		return "", err
	}
	return p, nil
}

func slugify(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b strings.Builder
	prevDash := false
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			prevDash = false
		default:
			if !prevDash {
				b.WriteRune('-')
				prevDash = true
			}
		}
	}
	return strings.Trim(b.String(), "-")
}

// RebuildIndex regenerates kb/index.md from current entries for fast lookup.
func (k *KB) RebuildIndex() error {
	all, err := k.List()
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Knowledge Base — Index\n\n")
	b.WriteString("<!-- Generated by `hatch kb index`. Tra cứu theo tag rồi mở file. -->\n\n")
	byType := map[string][]model.KBEntry{}
	for _, e := range all {
		byType[e.Type] = append(byType[e.Type], e)
	}
	for _, typ := range []string{model.KBDecision, model.KBDomain, model.KBLearning} {
		entries := byType[typ]
		if len(entries) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", strings.Title(typ))
		for _, e := range entries {
			tags := ""
			if len(e.Tags) > 0 {
				tags = " — `" + strings.Join(e.Tags, "` `") + "`"
			}
			fmt.Fprintf(&b, "- [%s](%s) %s%s\n", e.ID, e.Path, e.Title, tags)
		}
		b.WriteString("\n")
	}
	return os.WriteFile(k.L.KBIndex(), []byte(b.String()), 0o644)
}
