package compile

import (
	"fmt"
	"strings"
)

// genHeader marks a file as compiler output that must not be hand-edited.
const genHeader = "<!-- GENERATED BY `hatch compile` — DO NOT EDIT.\n" +
	"     Source of truth: .hatch/{charter.md,roles/,registry.yaml}.\n" +
	"     Edit the SSOT then re-run `hatch compile`. -->"

// Render produces the instruction-file content for a bundle, applying
// L0 (mission) + L1 (roles) + L2 pointers layering.
func Render(b Bundle) string {
	var w strings.Builder

	// Kiro steering files take YAML frontmatter selecting the inclusion mode.
	if b.Surface.Key == "kiro" {
		w.WriteString("---\ninclusion: always\n---\n\n")
	}

	w.WriteString(genHeader + "\n\n")

	title := "Hatch — Agent Operating Context"
	if b.Project != "" {
		title = b.Project + " — Agent Operating Context"
	}
	fmt.Fprintf(&w, "# %s\n\n", title)

	if len(b.Agents) > 0 {
		names := make([]string, len(b.Agents))
		for i, a := range b.Agents {
			names[i] = a.ID
		}
		fmt.Fprintf(&w, "_Surface: %s · read by: %s_\n\n", b.Surface.Desc, strings.Join(names, ", "))
	}

	// L0 — mission, loaded every message.
	w.WriteString("## Mission (L0)\n\n")
	if b.Charter != "" {
		w.WriteString(b.Charter + "\n\n")
	} else {
		w.WriteString("_No charter.md yet._\n\n")
	}

	// L1 — the roles this agent may hold.
	w.WriteString("## Your roles (L1)\n\n")
	w.WriteString("Bạn có thể giữ các vai dưới đây. **Vai hiện hành do ticket bạn claim quyết định** — đọc frontmatter `role` của ticket.\n\n")
	for _, rc := range b.Roles {
		t := rc.Role.Title
		if t == "" {
			t = rc.Role.ID
		}
		fmt.Fprintf(&w, "### Role: %s (`%s`)\n\n", t, rc.Role.ID)
		if rc.Body != "" {
			w.WriteString(rc.Body + "\n\n")
		} else {
			fmt.Fprintf(&w, "_Chưa có roles/%s.md._\n\n", rc.Role.ID)
		}
	}

	// L2 — pointers only; the agent reads these on demand when it claims work.
	w.WriteString("## Context map (L2 — đọc on-demand, KHÔNG nạp sẵn)\n\n")
	w.WriteString("Khi claim ticket, đọc `context_refs` của ticket + các nguồn liên quan dưới đây. Tra Knowledge Base trước khi suy diễn lại.\n\n")
	if len(b.ContextRefs) > 0 {
		for _, r := range b.ContextRefs {
			fmt.Fprintf(&w, "- `.hatch/%s`\n", r)
		}
		w.WriteString("\n")
	}
	w.WriteString("- Board: `.hatch/board/<lane>/` — ticket bạn đang làm.\n")
	w.WriteString("- Knowledge Base: `.hatch/kb/index.md` — quyết định & bài học chung.\n")
	w.WriteString("- Protocol: `.hatch/protocol/` — claim/lock, handoff, DoD.\n\n")

	// Operating rules shared by every surface.
	w.WriteString("## Operating protocol\n\n")
	w.WriteString("- Một ticket một branch; claim = `git mv` vào `in-progress/` + push ngay (push thắng = lock thắng).\n")
	w.WriteString("- Mọi chuyển trạng thái để lại entry ledger (`why` bắt buộc) trong cùng commit.\n")
	w.WriteString("- Không sửa file ngoài `context_refs` đã khai; mở rộng scope thì cập nhật ticket trước.\n")
	w.WriteString("- Đổi assignee/role ⇒ ghi Handoff notes. Tri thức đáng giữ ⇒ ghi KB.\n")

	out := w.String()
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return out
}
